name: "Check PR for podcast update"
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  pr_update_podcast:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: parse PR for podcast update
        uses: pcarion/podcast-directory-action@master
        with:
          podcast-yaml-directory: 'podcasts'
          repo-token: ${{ secrets.GH_PAT }}
