name: "Check PR for podcast update"
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  pr_update_podcast:
    runs-on: ubuntu-latest
    steps:
      - name: parse PR for podcast update
        uses: pcarion/podcast-directory-action@v0.7
        with:
          podcast-yaml-directory: 'podcasts'
          podcast-json-directory: 'netlify/www/content/podcasts'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

